config/routes.rb
def draw_path_prefix path=nil
  # :recognize_route_path_prefix stored in defaults is something I made up
  # This is done this way because need a way to break up routes file in a nested manner
  # and the @scope[:defaults] is cleared out in different scopes so it gives us the ability
  # to specify where to lookup the files when in a nested context
  # Otherwise there is no way to know the path for the lookup of the files in the call to #draw
  if path.present?
    @scope[:defaults][:recognize_route_path_prefix] = path if @scope[:defaults].kind_of?(Hash)
  else
    (@scope[:defaults].present? && @scope[:defaults][:recognize_route_path_prefix].present?) ? @scope[:defaults][:recognize_route_path_prefix]+"/" : ""
  end
end

def draw route
  instance_eval(File.read(Rails.root.join("config/routes/#{draw_path_prefix}#{route}.rb")))
end

Rails.application.routes.draw do

  # this definition should be placed at the beginning to override all the relevant redirect-able www routes
  draw :www_redirection_route

  resources :surveys, except: [:new, :edit]
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  use_doorkeeper

  resources :inbound_emails, only: [:create]
  resources :chat_threads
  resources :chat_messages

  # API ROUTES
  draw :api_routes
  # Simple Tags resource
  resources :tags, only: [:index]

  root :to => "home#index", :constraints => LoggedInConstraint.new(:logged_out_route)
  root :to => "recognitions#index", :constraints => LoggedInConstraint.new(:logged_in_route), as: :authenticated_root

  get '/proxy.html' => "home#proxy"

  # MISC ROUTES
  resources :password_resets, except: [:destroy]
  resources :support_emails, only: [:new, :create]

  get '/images', to: redirect("/images/default.png")
  get '/support/thanks', to: 'support_emails#support_thanks', as: :support_thanks
  get '/sales/thanks', to: 'support_emails#sales_thanks', as: :sales_thanks
  get '/contact', to: 'support_emails#new', as: :contact
  get '/sales', to: 'support_emails#sales', as: :contact_sales
  get '/sales_simple', to: 'support_emails#sales_simple', as: :sales_simple
  get '/auth/office365', to: redirect("http://recognizeapp.com/auth/microsoft_graph")

  # WORKPLACE ROUTES
  get '/fb_workplace/start', to: 'fb_workplace#start', as: :workplace_start
  get '/fb_workplace/callback', to: 'fb_workplace#callback', as: :workplace_callback
  get '/fb_workplace/failure', to: 'fb_workplace#failure', as: :workplace_failure
  # get '/fb_workplace/deauth', to: 'fb_workplace#deauth', as: :workplace_deauth
  # post '/fb_workplace/deauth', to: 'fb_workplace#deauth'
  match "/fb_workplace/deauth" => "fb_workplace#deauth", as: :workplace_deauth, via: [:get, :post]

  #unsubscribe routes
  match "/unsubscribe/:token", to: "users#unsubscribe", as: :unsubscribe, via: [:get, :patch]

  # MS TEAMS ROUTES
  draw :ms_teams_routes

  # FILE ROUTES
  get '/extensions/recognize.xpi', to: 'files#firefox_extension'

  #ADMIN ROUTES
  draw :admin_routes

  #SESSION ROUTES
  draw :session_routes

  #AUTHENTICATION ROUTES
  draw :authentication_routes

  # STATIC PATHS
  draw :static_routes

  # LANDING PAGES PATHS
  draw :landing_page_routes

  # COMPANY SCOPED ROUTES
  draw :company_routes

  # RECOGNITION ROUTES
  draw :recognition_routes

  # SIGNUP ROUTES
  draw :signup_routes

  draw :cms_routes

  draw :award_generator_routes

  draw :stream_async_routes

  resource :account_chooser, controller: :account_chooser, only: [:show, :update]

  resources :comments

  # This is overriden if there is a robots.txt in `public/ folder`, and it is the preferred method.
  get 'robots.txt' => "home#robots"

  get 'progress-job/:job_id' => 'progress_job/progress#show'

  get "/:network", to: "application#routing_error", constraints: {:network => /[^\/]+/} , format: false
  get "/:network*path", to: "application#routing_error", constraints: {:network => /[^\/]+/} , format: false

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  enable_captcha only: [:sign_up]

  include CmsConcern
  cms_action :videos, :resources, :outlook, :features

  attr_accessor :awards, :pricing, :privacy_policy, :analytics,
                :terms_of_use, :contest, :gamification, :engagement,
                :customizations, :getting_started, :mobile, :slack,
                :yam_gam, :download

  def index
    @homepage_h1 = 'Customized to Your Company. Integrated Into Your Tools.'
    @homepage_image = 'pages/home-index/recognize-stream-2020.jpg'

    @user_session = UserSession.new
    @support_email = SupportEmail.new
    @support_email.type = params[:type]
    @user = find_or_initialize_user

    #the session may contain an email of user that is
    #all setup and ok to login
    if @user.ok_to_login?
      #if so, then clear out of session and present a new user
      session.delete(:email)
      session.delete(:phone)
      session.delete(:email_network)
      @user = User.new
    end
    @pageName = "marketing-home"
  end

  def videos
    @cms_videos = wp_client.videos
  end

  def demo_survey
    page_title = "Employee Recognition Report"
    page_description = "Trends and preferences towards an employee recognition and rewards program based on a survey of over 1,000 people."
  end

  def employee_recognition_programs

  end

  def reward_ideas
  end

  def is_logged_in
    render :layout => false
  end

  def rewards
    page_description = "Recognize provides an effecive employee recognition rewards app to provide a result to your employee recognition points. Visit us today."
  end

  def employee_nominations
    page_title = "Employee Award Nomination Software"
    page_description = "If you are looking for reliable employee award nomination software, visit Recognize today and learn more about the features we can offer!"
  end

  def icons
  end

  def fb_workplace
  end

  def incentives
    page_title = "Employee Incentive Program App"
    page_description = "If you are looking for a reliable employee incentive program app, visit Recognize to learn more about all of the features we have to offer!"
  end

  def resources
    @cms_resources = wp_client.resources
  end

  def office365
  end

  def outlook
    @post = wp_client.get_post(76)
  end

  def sharepoint
  end

  def engagement_report
  end

  def anniversaries
  end

  def distributed_workforce_infographic
  end

  def tour
    @user = User.new(company: Company.new)
  end

  def sign_up
    return redirect_to root_path if @current_user

    @user = find_or_initialize_user
  end

  def features
    @features = wp_client.feature_categories
  end

  def about
    @user = User.new(company: Company.new)
  end

  def extension
    @user = User.new(company: Company.new)
  end

  def why
    @user = User.new(company: Company.new)
  end

  def user_rights
  end

  def cookies_policy
  end

  def glossary
  end

  def healthcare_landing
  end

  def banking_landing
  end

  def microsoft_teams_landing
    @title = "Employee Recognition for Microsoft Teams"
    @intro_description = "Engage staff in Microsoft Teams and Office 365 with a formal on-the-spot bonus employee recognition program."
    @main_image = "pages/home-microsoft-teams-landing/dashboard.jpg"
  end

  #a view of the maintenance page for development
  def maintenance
    render action: "maintenance", layout: false
  end

  def upgrade
    if current_user.present?
      opts = {network: current_user.network}
      opts[:code] = params[:code] if params[:code].present?
      redirect_to upgrade_path(opts)
    else
      flash[:notice] = "Please login to upgrade your account"
      store_location
      redirect_to login_path
    end
  end

  def robots
    render action: "robots", layout: false
  end

  def proxy
    render action: "proxy", layout: false
  end

  def outlook_addin
    response.headers.except! 'X-Frame-Options'

    render action: "outlook_addin", layout: false
  end

  def fb_workplace_placeholder
    response.headers.except! 'X-Frame-Options'

    render action: "fb_workplace_placeholder", layout: false

  end
  protected

  def use_marketing_layout?
    true
  end

  def is_home?
    true
  end

  def find_or_initialize_user
    opts = {}
    opts[:network] = session[:email_network] if session[:email_network]
    opts[:phone] = session[:phone] if session[:phone]
    opts[:email] = session[:email] if session[:email]
    return User.find_or_initialize_by(**opts) if opts.present?

    User.new(company: Company.new)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_bottom.html.erb
<% unless current_user.present? %>
  <div class="relative">
    <%= render :partial => "email_form", locals: {title: "Add employee recognition to your company's workflow"} %>
  </div>
<% end %>

app/views/home/_extension_download.html.erb
<div id="marketing-browser-extensions-info" class="marginBottom40">
  <div class="centered" data-turbolinks="false">
    <h3>Download the Recognize extension &amp; replace Yammer Praise</h3>
    <p class="marginBottom30"><a href="/recognize_ie_extension_user_guide.pdf">Read the IE installation guide</a>.</p>
    <div class="table">
      <%= link_to chrome_extension_url, id: "chrome", class: "item" do %>
        <h4 class="balance-text">Google Chrome Recognize extension</h4>
        <%= image_tag "pages/home-extension/chrome.png", alt: "Google Chrome browser" %>
        <div class="button button-large button-no-chrome block">Install into Chrome</div>
      <% end %>
      <a href="/RecognizeAppIESetup.exe" id="ie" class="item">
        <h4 class="balance-text">Microsoft Internet Explorer Recognize extension</h4>
        <%= image_tag "pages/home-extension/ie.png", alt: "Microsoft Internet Explorer" %>
        <div class="button button-large button-no-chrome block">Install into IE 11 or IE 10</div>
      </a>
      <%= link_to "https://www.microsoft.com/en-us/p/recognize/9p1t0vb997s7", id: "edge", class: "item" do %>
        <h4 class="balance-text">Microsoft Edge Recognize extension</h4>
        <%= image_tag "pages/home-extension/edge.png", alt: "Microsoft Edge" %>
        <div class="button button-large button-no-chrome block">Install into Edge</div>
      <% end %>
      <%= link_to "/recognize.safariextz", id: "safari", class: "item" do %>
        <h4 class="balance-text">Apple Safari Recognize extension</h4>
        <%= image_tag "pages/home-extension/safari.png", alt: "Safari" %>
        <div class="button button-large button-no-chrome block">Install into Safari</div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_video.html.erb
<li>

  <h2><%= video[:snippet][:title] %></h2>
  <p class="marginBottom30"><%= video[:snippet][:description].html_safe %></p>

  <div class="youtube-video" data-id="<%= video[:snippet][:resourceId][:videoId] %>" data-width="100%" data-play="stop"></div>

</li>

app/views/home/anniversaries.html.erb
<% content_for :meta_properties do %>
  <meta property="og:title" content="Automated Work Service Anniversaries & Employee Birthday Rewards" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Recognizeapp.com" />
  <meta property="og:description" content="An easy-to-use, automatic employee recognition program for birthday and anniversaries." />
  <meta property="og:image" content="/assets/pages/home-mobile/stream.jpg" />
<% end%>

<% content_for :title, "Work Anniversary Recognition" %>
<% content_for :description, "Off-the-shelf solution to the most common form of employee recognition. Give rewards and comment on anniversaries from easy-to-use apps." %>
<% content_for :meta_keywords, "Employee Service Awards, Employee birthday rewards, staff anniversaries, employee anniversaries" %>

<div class="banner">
  <div class="inner">
    <div>
      <h1>Work Anniversary Program &amp; Employee Birthday Recognition</h1>
      <p class="tagline">Start an all-star program with automatic <%= link_to "rewards", rewards_path %> and a social feed of work anniversaries.<br>
        Configurable, enterprise solution for the most common form of employee recognition.</p>
    </div>
    <div class="buttons">
      <%= schedule_demo_link css_classes: 'button button-large' %>

    </div>
  </div>

  <%= lazy_image_tag "pages/home-anniversaries/badges.png", alt: "All the work anniversary graphics for a birthday or anniversary" %>
</div>

<div class=" padding30">

    <div class="steps-wrapper">
      <div class="text-center marginBottom30">
        <h2>Three Easy Steps</h2>
      </div>

      <ul class="anniversary-steps">
        <li>
          <%= lazy_image_tag "pages/home-anniversaries/icon-address.png", alt: "Birthday icon" %>
          <p>Import your staff’s start dates & birthdays with Office 365, sFTP, spreadsheet, or manually.</p>
        </li>
        <li>
          <%= lazy_image_tag "pages/home-anniversaries/icon-birthday.png", alt: "Address icon" %>
          <p>Choose which work anniversaries to activate: one week to sixty years. Add personalized messages and images to each event.</p>
        </li>
        <li>
          <%= lazy_image_tag "pages/home-anniversaries/icon-glass.png", alt: "Rewards icon" %>
          <p>Choose rewards staff can redeem with the points they earn, such as gift cards (Visa, Amazon, Starbucks) or company items (Paid Time Off, Sweatshirt).</p>
        </li>
      </ul>
    </div>



<!--    <div class="plan__price">-->
<!--      <span class="plan__price__starting">Starting at</span>-->
<!--      <span class="plan__price__price"><span class="plan_price_value">$390</span><sup class="plan__price__decimals_currency"><span class="plan__price__decimals"></span><span class="plan__price__currency">(USD)</span></sup></span>-->
<!--      <span class="plan__price__duration">/year</span>-->
<!--      <span class="plan__price__risk">Risk-free for 60 days.</span>-->
<!--      <hr class="hr">-->
<!--      <ul class="check-list">-->
<!--        <li class="balance-text" style="">400+ international gift cards</li>-->
<!--        <li class="balance-text" style="">Add your own rewards</li>-->
<!--        <li class="balance-text" style="">Individual or company-wide privacy for birthday or anniversaries</li>-->
<!--        <li class="balance-text" style="">Inside Outlook, Office 365, Sharepoint, TVs, SMS, Workplace by Facebook, Okta &amp; many others</li>-->
<!--        <li class="balance-text" style="">Automatic notifications for managers or specific roles</li>-->
<!--        <li class="balance-text" style="">Customizable emails &amp; web app</li>-->
<!--        <li class="balance-text" style="">Secure &amp; scalable. USA-based company</li>-->
<!--      </ul>-->
<!--    </div>-->

</div>

<div id="points">
  <section id="stream">
    <div class="inner">
      <div class="row-fluid flex-centered">
        <div class="span5">
          <h2 class="balance-text">Employee service program visible to everyone</h2>
          <p class="tagline balance-text">The Recognize platform is social or private for work anniversaries. Whenever someone has a work anniversary, the whole company can see in the Recognize stream, which you can display in your intranet or a tv in your lobby. Staff can also choose to have their events private where they still get points but only they can see it.</p>

          <p>Staff can also view, comment, or like the work anniversaries from the <%= link_to "Recognize mobile app", mobile_path %>, Workplace by Facebook, Outlook, and more.</p>
        </div>
        <div class="span7">
          <%= lazy_image_tag "pages/home-mobile/stream.jpg", alt: "Viewing the work years of service awards in an app that allows people to comment or like the recognitions." %>
        </div>
      </div>
    </div>
  </section>

  <section id="integrations">
    <div class="inner">
      <div class="row-fluid">
        <div class="span4">
          <%= lazy_image_tag "pages/home-anniversaries/fb-workplace-logo.png", alt: "Workplace by Facebook logo" %>
          <h2 class="balance-text">
            Work anniversary program in <%= link_to "Workplace by Facebook", fb_workplace_path %>
          </h2>
          <p class="tagline balance-text">Recognize provides the entire work anniversary program within Workplace by Facebook. Staff receive private messages in Workplace Chat when it is their special day. It will show the message you have created. Plus, it provides them a way to redeem rewards inside Workplace. Managers are also notified in Workplace of their direct reports work anniversary or birthday. There are plenty of ways to share the events on Workplace.</p>
        </div>
        <div class="span4">
          <%= lazy_image_tag "pages/home-anniversaries/mobile-icon.png", alt: "Mobile smart phone icon" %>
          <h2 class="balance-text">Work anniversary program in mobile</h2>
          <p class="tagline balance-text">Download the well designed <%= link_to "mobile app", mobile_path %> from Recognize. Staff receive work anniversary from the mobile app on their special day. Your staff can access their reward redemptions from the Recognize mobile app. View colleague's public anniversaries or birthday events to comment or like. For users that don't download the Recognize mobile app, companies can set up SMS notifications and utilize the mobile web app.</p>
        </div>
        <div class="span4">
          <%= lazy_image_tag "pages/home-anniversaries/office365-logo.png", alt: "Office 365 logo" %>

          <h2 class="balance-text">Work anniversary program in <%= link_to "Office 365", office365_path %></h2>
          <p class="tagline balance-text">Utilize user sync, SSO, Sharepoint,  <%= link_to "Yammer", extension_path %>, and  <%= link_to "Outlook", marketing_outlook_path %> to create a highly visible work anniversary program. Recognize is the best employee recognition and rewards program in Office 365 with a number of different connections. Staff love accessing rewards in Outlook. They can comment or like the work anniversaries from a Sharepoint page or the Yammer feed. Recognize makes the anniversary program top of mind across various tools. Set up for IT takes 1/2 day or less.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="user_sync">
    <div class="inner">
      <div class="row-fluid flex-centered">
        <div class="span5">
          <h2 class="balance-text">Import employee anniversary dates with Office 365 or sFTP</h2>
          <p class="tagline balance-text">Recognize has user sync abilities with Office 365, SSO, and Yammer. You can always do an import and update via spreadsheets.</p>
        </div>
        <div class="span7">
          <%= lazy_image_tag "pages/home-anniversaries/sync.png", alt: "Enable user sync with a few clicks with Office 365 to capture work anniversary dates." %>
        </div>
      </div>
    </div>
  </section>
  <section id="setup">
    <div class="inner">
      <div class="row-fluid flex-centered">
        <div class="span5">
          <h2 class="balance-text">Takes five minutes to set up the Recognize employee service program</h2>
          <p class="tagline balance-text">The admin completes a one-time setup to insert which years to celebrate, what the message will be, and how much each event is worth in a systematic way. Plus, upload a graphic or gif to symbolize each event.</p>
        </div>
        <div class="span7">
          <%= lazy_image_tag "pages/home-anniversaries/setup.png", alt: "Shows easy setup choices, such as enabling specific events like first year of service recognition.", class: "shadow" %>
        </div>
      </div>
    </div>
  </section>

  <section id="birthday">
    <div class="inner">
      <div class="row-fluid flex-centered">
        <div class="span5">
          <h2 class="balance-text">Automatic employee celebration in your work anniversary program</h2>
          <p class="tagline balance-text">Your staff can update their Recognize profile to include their birthday and start date for recognition. Each employee can choose their privacy settings for anniversaries or birthday. At the start of the program, admins can choose to make all anniversaries or birthdays private. It all depends on you.</p>
        </div>
        <div class="span7">
          <%= lazy_image_tag "pages/home-anniversaries/birthdays.png", alt: "Showing automatic birthday recognition." %>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="inner">
      <div class="row-fluid flex-centered">
        <div class="span5">
          <h2 class="balance-text">Manager Service Manager Reporting</h2>
          <p class="tagline balance-text">Managers have a calendar list view of all their direct report anniversaries and birthdays. Admins can see the entire company.</p>
        </div>
        <div class="span7">
          <div class="youtube-video" data-id="te5En1ocSvU"></div><br>
        </div>
      </div>
    </div>
  </section>



  <%= render partial: "marketing_cta_banner" %>
</div>

<%= render partial: 'home/footer' %>
<%= render partial: "layouts/youtube_load" %>

app/views/home/download.html.erb
<%= content_for :title, "Download browser extensions for recognition program" %>
<%= content_for :description, "Integrate your employee recognition and rewards programs using the Recognize mobile app and Chrome extensions." %>

<section id="intro" class="marginBottom40">
  <div class="inner">
    <h1 class="balance-text">Recognize Downloads</h1>
    <p class="tagline marginBottom10 balance-text">Download our browser extension for ease of use and integration into Yammer.</p>
    <%= link_to "Contact Us", contact_path, class: "button button-primary button-large" %>
  </div>
  <%= render partial: "home/patterns/ice.svg" %>
</section>

<div id="points">
  <%= render partial: "extension_download" %>
</div>

app/views/home/getting_started.html.erb
<div id="intro-wrapper">
  <h1>Getting Started</h1>
</div>
<%= render :partial => 'footer' %>

app/views/home/office365.html.erb
<%= render partial: "layouts/office_script_tag" if outlook_viewer? %>
<%= content_for :body_attributes, 'data-turbolinks=false' if outlook_viewer? %>

<% content_for :meta_properties do %>
  <meta property="og:title" content="Office 365 employee recognition app. Turnkey solution for Outlook, Sharepoint, Yammer, & Azure." />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Recognizeapp.com" />
  <meta property="og:description" content="Strengthen Employee Engagement through Employee Recognition, Service Anniversaries, Employee Rewards, Employee Nominations inside Office 365." />
  <meta property="og:image" content="/assets/pages/home-office365/desktop-mobile.png" />
<% end%>

<% content_for :title, "Office 365 Employee Recognition" %>
<% content_for :description, "A Turnkey Employee Recognition & Rewards Solution inside Outlook, Sharepoint, Microsoft Teams, Azure, and Yammer." %>
<% content_for :meta_keywords, "Office 365 Suite, Sharepoint, Yammer, Outlook add-ins, Outlook Employee Recognition, Sharepoint Employee Recognition, Yammer Employee Recognition" %>

<% if params[:viewer].blank? %>
  <section class="masthead padding30">
    <div class="recognize-marketing-header flex">
      <div class="text-desc">
        <h1>
          <span class="recognize-color">Recognize</span>
          <strong class="balance-text">The Microsoft 365 Engagement Provider</strong>
        </h1>
        <p class="balance-text tagline">Why should your staff go to another set of tools when you already have Office 365? The Recognize employee engagement platform comes to your where your employees work. That's why Recognize is integrated with five Microsoft apps. We are dedicated to provide a seamless experience for your employees.</p>
        <%= schedule_demo_link %>
      </div>
      <div class="svg-image">
        <svg width="1920px" height="400px" viewBox="0 0 1920 400" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"> 
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="O365-page" transform="translate(0.000000, -226.000000)" fill="#D1D9DC">
              <path d="M787.840442,359 C1028.36943,294.12367 1231.75595,249.790337 1920,226 L1920,626 L-265.316406,626 C196.259167,512.87633 547.311449,423.87633 787.840442,359 Z" id="Rectangle"></path>
            </g>
          </g>
        </svg>
        <%= lazy_image_tag "pages/home-office365/desktop-mobile.png", alt: "Recognize is available on Microsoft Teams mobile and desktops."%>
      </div>
    </div>
  </section>

  <section class="apps-wrapper">
    <h2 class="centered balance-text width-500 margin-auto">Make Office 365 the hub for employee engagement</h2>
    <ul class="apps-list">
      <li class="app">
        <%= lazy_image_tag "pages/home-office365/azure.png", alt: "Microsoft Azure logo", style: "padding-top: 50px"%>
        <p>Recognize Provides a daily or weekly sync to Azure Active Directory. This enables your company to automatically add and remove employees.</p>
        <%= link_to "Learn more", "https://azuremarketplace.microsoft.com/en-us/marketplace/apps/aad.recognize" %>
      </li>
      <li class="app">
        <%= lazy_image_tag "pages/home-office365/teams.png", alt: "Microsoft Teams logo", style: "padding-top: 50px"%>
        <p>Recognize MS Teams integration brings recognition and rewards to your main communication tool.</p>
        <%= link_to "Learn more", microsoft_teams_employee_recognition_path %>
      </li>

      <li class="app">
        <%= lazy_image_tag "pages/home-office365/outlook.png", alt: "Microsoft Outlook logo", style: "padding-top: 50px"%>
        <p>Recognize outlook integration super charges Outlook into an employee engagement platform.</p>
        <%= link_to "Learn more", marketing_outlook_path %>
      </li>
      <li class="app">
        <%= lazy_image_tag "pages/home-office365/sharepoint.png", alt: "Microsoft Sharepoint logo", style: "padding-top: 50px"%>
        <p>Recognize sharepoint app can be a side panel or full screen experience inside sharepoint.</p>
        <%= link_to "Learn more", sharepoint_path %>
      </li>
      <li class="app">
        <%= lazy_image_tag "pages/home-office365/yammer.png", alt: "Microsoft Yammer logo.", style: "padding-top: 50px"%>
        <p>Recognize Yammer integration uses a browser integration for Chrome and Edge to put Recognize inside Yammer.</p>
        <%= link_to "Learn more", extension_path %>
      </li>
    </ul>
  </section>

  <%= link_to "https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/recognize-tutorial", class: 'tutorial flex width-800 justify-content-space padding20 align-items-center', html: {'_target': 'blank'} do %>
    <div>
      <%= lazy_image_tag "pages/home-office365/peter.jpg", alt: "Peter Philips, Recognize" %>
    </div>
    <div>
      <p class="cta"><strong>Microsoft Tutorial:</strong> <span class="recognize-color">Azure Active Directory Integration with Recognize</span></p>
      <p>By Peter Philips, Recognize CTO</p>
    </div>

    <div class='arrow-right'>
      <%= feather_icon('chevron-right', {width: 100, height: 200, 'stroke-width': 0.5 }) %>
    </div>
  <% end %>

  <section class="quote-section flex width-800 margin-auto quote-box-side justify-content-center">
    <div class="quote-box-image-wrapper">
      <%= lazy_image_tag('pages/home-office365/employee.jpg') %>
    </div>
    <div class="quote-box">
      <quote class="h2">Recognize inside Microsoft Teams makes promoting company values front and center.
      </quote>
      <p>Nick Martin<br><span class="subtle-text">Manager Home Depot</span></p>
    </div>
  </section>

  <hr class="margin-auto marginBottom50"/>

  <section class="contact marginBottom100 centered width-800 margin-auto">
    <h2 class="balance-text">Recognize Microsoft integrations are included in all subscriptions</h2>
    <%= link_to "Contact us", contact_sales_path, class: "button button-primary button-large" %>
  </section>
</div>

<%= render partial: "home/footer" %>

<% else %>

  <section class="masterhead clearfix">
    <div class="sign-up centered">

      <div class="inner">
        <% if params[:viewer] == "outlook" %>
          <%= lazy_image_tag('chrome/logo-72x72.png', width: 50) %>
          <h2 class="balance-text">Employee recognition &amp; rewards <i>for Outlook</i></h2>
          <p class="tagline balance-text">Sign in with your Microsoft login. You don't need to be a user of Recognize to login!</p>
        <% else %>
          <h2 class="balance-text"><%= t(".title_html") %></h2>
          <p class="tagline">Anyone can sign in! Create a free account by signing in with Microsoft.</p>
        <% end %>

        <% if current_user.blank? %>

          <div class="sign-up-buttons">
            <%= link_to_o365 t("dict.login_microsoft"), redirect: root_path(close_on_open: true), class: "button button-o365-plain" %>
          </div>

        <% else %>
          <%= link_to t(".learn_about_outlook"), marketing_outlook_path, class: "button button-o365-plain" %>
          <%= link_to t(".learn_about_azure"), "https://azuremarketplace.microsoft.com/en-us/marketplace/apps/aad.recognize", class: "button button-o365-plain" %>
      <% end %>
      </div>
    </div>

    <div id="loading" class="displayNone centered padding3em">
      <%= lazy_image_tag "icons/outlook-progress.gif", alt: "Signing in to Recognize", class: "marginBottom10" %>
      <p class="text"><%= t("home.office365.talking_to_microsoft") %></p>
    </div>
  </section>

<% end %>